### PR TITLE
remove deprecate warning

### PR DESCRIPTION
**Pull request by txssseal**
This is making it unbearably hard to find failures in mono tests.  According to @dvictory this was more of a reminder, and it will be ok to remove.

### CODE REVIEW

**Comment by jspies** [comment]
It's supposed to make it unbearably hard. That's the point. Instead of removing the warning, you should fix the things triggering it.

**Comment by txssseal** [comment]
@jspies Derek looked into and apparently we are unable to actually fix it.  This would be the actual fix.

**Comment by jspies** [comment]
Pretty sure the fix is deprecating feature flip 1 and removing the check for FLIP_USE_API from the gem.

**Comment by txssseal** [comment]
right, but we are not deprecating flip 1 anytime soon are we?  And if we are deprecating soon, couldn't we just get rid of this message since we will be doing it.

**Comment by txssseal** [comment]
alright nvm, @jcderr says we are potentially doing it today.

**Comment by dvictory** [comment]
yeah I would keep this, you could add a check on the key value "flippy_use_api" to not throw the warning, then it will still throw it, but not every single time we us floppy

**Pull request closed without merging**
